# Pytorch
## Tensor 基础知识

In [9]:
import numpy as np
import torch

In [3]:
# 创建一个张量
x = torch.Tensor(3, 4)
print("Type: {}".format(x.type()))
print("Size: {}".format(x.shape))
print("Values: \n{}".format(x))  # print("Values: \n{}".format(x))


Type: torch.FloatTensor
Size: torch.Size([3, 4])
Values: 
tensor([[1.2516e-02, 0.0000e+00, 0.0000e+00, 0.0000e+00],
        [       nan, 4.2923e-41, 1.7753e+28, 7.1493e+22],
        [1.1989e+33, 7.0355e+22, 3.9615e+28, 3.8016e-39]])


``创建一个张量 x，它的形状是 (3, 4)，即 3 行 4 列。

注意：torch.Tensor() 会 返回一个未初始化的张量，即张量中的数值是内存中的随机值，不是全零或全一。``

In [ ]:
# 列表（List） → 张量

x = torch.zeros(2,3)
print(x)
x = torch.ones(2,3)
print(x)

tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])


In [10]:
# NumPy 数组 → 张量
y = np.random.rand(2, 3)
print(y)
x = torch.from_numpy(y)
print("Size: {}".format(x.shape)) 
print("Values: \n{}".format(x))

[[0.78215092 0.88463964 0.39280108]
 [0.46926138 0.34710096 0.7951139 ]]
Size: torch.Size([2, 3])
Values: 
tensor([[0.7822, 0.8846, 0.3928],
        [0.4693, 0.3471, 0.7951]], dtype=torch.float64)


🔍 总结
步骤	                                       说明
np.random.rand(2, 3)	            创建一个 2×3 的 NumPy 数组，包含 [0, 1) 的随机浮点数
torch.from_numpy(y)	                把 NumPy 数组转成张量，数据共享（不会复制）
.shape	                            查看张量的形状
.dtype	                            保留了 NumPy 的 float64 类型（不像默认 float32）


In [12]:
# 改变张量类型（张量默认为float类型）
x = torch.Tensor(3, 4)
print("Type: {}".format(x.type()))
x = x.long()
print("Type: {}".format(x.type()))

Type: torch.FloatTensor
Type: torch.LongTensor


# Tensor 运算

In [13]:
# 加法
x = torch.randn(2, 3)
y = torch.randn(2, 3)
z = x + y
print("Size: {}".format(z.shape)) 
print("Values: \n{}".format(z))

Size: torch.Size([2, 3])
Values: 
tensor([[ 1.1923, -1.1538,  1.2892],
        [ 0.0266,  0.3783,  1.9615]])


In [14]:
# 向量点积
x = torch.randn(2, 3)
y = torch.randn(3, 2)
z = torch.mm(x, y)
print("Size: {}".format(z.shape)) 
print("Values: \n{}".format(z))

Size: torch.Size([2, 2])
Values: 
tensor([[-2.5079, -4.4213],
        [ 0.0623,  1.3353]])


In [15]:
# 转置
x = torch.randn(2, 3)
print("Size: {}".format(x.shape)) 
print("Values: \n{}".format(x))
y = torch.t(x)
print("Size: {}".format(y.shape)) 
print("Values: \n{}".format(y))

Size: torch.Size([2, 3])
Values: 
tensor([[-1.7045, -0.0019, -0.6959],
        [-0.7181, -0.6192,  0.2743]])
Size: torch.Size([3, 2])
Values: 
tensor([[-1.7045, -0.7181],
        [-0.0019, -0.6192],
        [-0.6959,  0.2743]])


In [16]:
# Reshape
z = x.view(3, 2)
print("Size: {}".format(z.shape)) 
print("Values: \n{}".format(z))

Size: torch.Size([3, 2])
Values: 
tensor([[-1.7045, -0.0019],
        [-0.6959, -0.7181],
        [-0.6192,  0.2743]])


In [17]:
values, _ = torch.max(x, dim=0)

.transpose() 更通用，适用于多维张量。

它需要你显式指定两个维度要互换。

如果你对二维张量使用 .transpose(0, 1)，等价于 .t()。


🧠 你可以记住这句话：
dim=N 表示：对第 N 维“跨着”去求和，把这一维“压扁”掉了。



# 索引，切片和级联

In [19]:
x= torch.randn(3, 4)
print("x: \n{}".format(x))
print ("x[:1]: \n{}".format(x[:1]))
print ("x[:1, 1:3]: \n{}".format(x[:1, 1:3]))

x: 
tensor([[ 1.4162, -1.5315,  0.0163,  1.3601],
        [ 1.4041,  1.2902,  0.9746, -0.6042],
        [ 1.3510,  0.0393, -0.2837,  0.8712]])
x[:1]: 
tensor([[ 1.4162, -1.5315,  0.0163,  1.3601]])
x[:1, 1:3]: 
tensor([[-1.5315,  0.0163]])


In [ ]:
# 选择维度索引
x = torch.randn(2, 3)
print("Values: \n{}".format(x))
col_indices = torch.LongTensor([0, 2])
chosen = torch.index_select(x, dim=1, index=col_indices) # 第0和第2列的值
print("Values: \n{}".format(chosen)) 
row_indices = torch.LongTensor([0, 1])
chosen = x[row_indices, col_indices] # 来自（0,0）和（2,1）的值
print("Values: \n{}".format(chosen)) 

In [22]:
# 级联
x = torch.randn(2, 3)
print("Values: \n{}".format(x))
y = torch.cat([x, x], dim=0) # 按行堆叠（dim = 1按列堆叠）
print("Values: \n{}".format(y))

Values: 
tensor([[-0.7532, -1.2837,  1.5405],
        [ 0.9681,  1.3670,  0.4629]])
Values: 
tensor([[-0.7532, -1.2837,  1.5405],
        [ 0.9681,  1.3670,  0.4629],
        [-0.7532, -1.2837,  1.5405],
        [ 0.9681,  1.3670,  0.4629]])


# 梯度
y=3x+2
 
z=∑y/N
∂(z)/∂(x)=∂(z)/∂(y) ∂(z)/(x)=1/N∗3=1/12∗3=0.25

In [ ]:
# 带有gradient bookkeeping的张量
x = torch.rand(3, 4, requires_grad=True)
y = 3*x + 2
z = y.mean()
z.backward() # z是标量
print("Values: \n{}".format(x))
print("x.grad: \n", x.grad)

Values: 
tensor([[0.4809, 0.2861, 0.7074, 0.8419],
        [0.9368, 0.9966, 0.0825, 0.9824],
        [0.3913, 0.5373, 0.6326, 0.1971]], requires_grad=True)
x.grad: 
 tensor([[0.0802, 0.0477, 0.1179, 0.1403],
        [0.1561, 0.1661, 0.0138, 0.1637],
        [0.0652, 0.0896, 0.1054, 0.0329]])


In [24]:
# CUDA可用吗？
print (torch.cuda.is_available())

True


# 如果上面的代码返回False，那么请转到菜单栏上的Runtime→Change runtime type并在Hardware accelerator下选择GPU

In [25]:
# 创建一个CPU版的0张量
x = torch.Tensor(3, 4).to("cpu")
print("Type: {}".format(x.type()))

Type: torch.FloatTensor


In [26]:
# 创建一个CUDA版的0张量
x = torch.Tensor(3, 4).to("cuda")
print("Type: {}".format(x.type()))

Type: torch.cuda.FloatTensor


In [29]:
import torch

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

print(f"当前使用设备: {device}")
print(f"CUDA 可用: {torch.cuda.is_available()}")
if torch.cuda.is_available():
    print(f"GPU 名称: {torch.cuda.get_device_name(0)}")

    # 检查是否支持 TensorFloat-32
    tf32_supported = torch.backends.cuda.matmul.allow_tf32
    print(f"支持 TF32（TensorFloat-32）: {tf32_supported}")

    # 检查半精度是否可用（FP16）
    try:
        a = torch.randn((1000, 1000), dtype=torch.float16, device=device)
        b = torch.matmul(a, a)
        print("支持 FP16 运算 ✅")
    except RuntimeError:
        print("不支持 FP16 运算 ❌")

    # 检查双精度（FP64）
    try:
        a = torch.randn((1000, 1000), dtype=torch.float64, device=device)
        b = torch.matmul(a, a)
        print("支持 FP64 运算 ✅")
    except RuntimeError:
        print("不支持 FP64 运算 ❌")


当前使用设备: cuda
CUDA 可用: True
GPU 名称: NVIDIA GeForce RTX 2050
支持 TF32（TensorFloat-32）: False
不支持 FP16 运算 ❌
不支持 FP64 运算 ❌


In [30]:
import torch
x = torch.tensor([1.23])     # 默认 dtype=torch.float32
print(x.dtype) 

torch.float32
